// Generated by CoffeeScript 1.4.0
(function() {
  var child1_startup, child2_startup, home_template_rendered, message_parent, ok_to_start_children, parent_startup, pollFor, rendered, _when;

  if (!Meteor.isClient) {
    return;
  }

  Template.renderPage.showHome = function() {
    return Session.equals('route', '/');
  };

  Template.renderPage.showChild1 = function() {
    return Session.equals('route', '/test1/child1');
  };

  Template.renderPage.showChild2 = function() {
    return Session.equals('route', '/test1/child2');
  };

  Meteor.startup(function() {
    Session.set('route', window.location.pathname);
    switch (window.location.pathname) {
      case '/':
        window.name = 'parent';
        return parent_startup();
      case '/test1/child1':
        window.name = 'child1';
        return child1_startup();
      case '/test1/child2':
        window.name = 'child2';
        return child2_startup();
    }
  });

  _when = window.when;

  pollFor = function(fn) {
    var check, deferred, timer;
    deferred = _when.defer();
    timer = null;
    check = function() {
      if (fn()) {
        if (timer != null) {
          clearInterval(timer);
        }
        timer = null;
        return deferred.resolve();
      }
    };
    timer = setInterval(check, 300);
    check();
    return deferred.promise;
  };

  ok_to_start_children = _when.defer();

  home_template_rendered = _when.defer();

  Session.set('ready', false);

  Session.set('done', false);

  Template.test1_home.ready = function() {
    return Session.get('ready');
  };

  Template.test1_home.done = function() {
    return Session.get('done');
  };

  rendered = false;

  Template.test1_home.rendered = function() {
    if (rendered) {
      return;
    }
    rendered = true;
    return home_template_rendered.resolve();
  };

  _when.join(home_template_rendered, ok_to_start_children).then(function() {
    return $('#iframes').append('<iframe id="child1" src="/test1/child1"></iframe>\n<iframe id="child2" src="/test1/child2"></iframe>');
  });

  parent_startup = function() {
    var child1_awake, child2_awake;
    pollFor(function() {
      return $('#child2-got-it')[0];
    }).then(function() {
      return Session.set('done', true);
    });
    child1_awake = pollFor(function() {
      return $('#child1-awake')[0];
    });
    child2_awake = pollFor(function() {
      return $('#child2-awake')[0];
    });
    _when.join(child1_awake, child2_awake).then(function() {
      return $('body', $('#child1')[0].contentWindow.document).append('<div id="begin">begin</div>');
    });
    Meteor.BrowserStore.set('foo', null);
    return ok_to_start_children.resolve();
  };

  message_parent = function(msg) {
    return $('body', window.parent.document).append("<div id=\"" + msg + "\">" + msg + "</div>");
  };

  child1_startup = function() {
    pollFor(function() {
      return $('#begin')[0];
    }).then(function() {
      return Meteor.BrowserStore.set('foo', 1234);
    });
    return message_parent('child1-awake');
  };

  child2_startup = function() {
    Meteor.autorun(function() {
      if (Meteor.BrowserStore.equals('foo', 1234)) {
        return message_parent('child2-got-it');
      }
    });
    return message_parent('child2-awake');
  };

}).call(this);
