// Generated by CoffeeScript 1.4.0
(function() {
  var add_event, child1_begin, child1_startup, child2_got_it, child2_startup, created_already, home_template_created, ok_to_start_children, parent_startup, _when;

  if (Meteor.isClient) {
    switch (window.location.pathname) {
      case '/':
        window.name = 'parent';
        Template.renderPage.showHome = function() {
          return true;
        };
        Meteor.startup(function() {
          return parent_startup();
        });
        break;
      case '/test1/child1':
        window.name = 'child1';
        Template.renderPage.showChild1 = function() {
          return true;
        };
        Meteor.startup(function() {
          return child1_startup();
        });
        break;
      case '/test1/child2':
        window.name = 'child2';
        Template.renderPage.showChild2 = function() {
          return true;
        };
        Meteor.startup(function() {
          return child2_startup();
        });
    }
    _when = window.when;
    add_event = function(type, handler) {
      if (window.addEventListener) {
        return window.addEventListener(type, handler, false);
      } else if (window.attachEvent) {
        return window.attachEvent(type, handler);
      }
    };
    ok_to_start_children = _when.defer();
    home_template_created = _when.defer();
    Session.set('ready', false);
    Session.set('done', false);
    Template.test1_home.ready = function() {
      return Session.get('ready');
    };
    Template.test1_home.done = function() {
      return Session.get('done');
    };
    created_already = false;
    Template.test1_home.created = function() {
      if (created_already) {
        throw new Error('oops already created');
      }
      created_already = true;
      return home_template_created.resolve();
    };
    _when.join(home_template_created, ok_to_start_children).then(function() {
      return $('#iframes').append('<iframe id="child1" src="/test1/child1"></iframe>\n<iframe id="child2" src="/test1/child2"></iframe>');
    });
    child2_got_it = function() {
      return Session.set('done', true);
    };
    parent_startup = function() {
      var child1_awake, child2_awake;
      child1_awake = _when.defer();
      child2_awake = _when.defer();
      add_event('message', (function(event) {
        switch (event.data) {
          case 'child1 is awake':
            return child1_awake.resolve();
          case 'child2 is awake':
            return child2_awake.resolve();
          case 'child2 got it':
            return child2_got_it();
        }
      }));
      _when.join(child1_awake, child2_awake).then(function() {
        return $('#child1')[0].contentWindow.postMessage('begin', '*');
      });
      Meteor.BrowserStore.clear();
      return ok_to_start_children.resolve();
    };
    child1_begin = function() {
      return Meteor.BrowserStore.set('foo', 1234);
    };
    child1_startup = function() {
      add_event('message', (function(event) {
        switch (event.data) {
          case 'begin':
            return child1_begin();
        }
      }));
      return window.parent.postMessage('child1 is awake', '*');
    };
    child2_startup = function() {
      Meteor.autorun(function() {
        if (Meteor.BrowserStore.equals('foo', 1234)) {
          return window.parent.postMessage('child2 got it', '*');
        }
      });
      return window.parent.postMessage('child2 is awake', '*');
    };
  }

}).call(this);
